# Generated by Django 4.2.7 on 2023-11-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0002_alter_member_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='purchased_by',
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftlist.member'),
        ),
    ]
