# Generated by Django 4.2.7 on 2023-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0003_remove_gift_purchased_by_alter_gift_gift_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='purchased',
        ),
        migrations.AddField(
            model_name='gift',
            name='is_shopper',
            field=models.BooleanField(default=False),
        ),
    ]
