# Generated by Django 4.2.7 on 2023-11-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0004_remove_gift_purchased_gift_is_shopper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='is_shopper',
        ),
        migrations.AddField(
            model_name='member',
            name='is_shopper',
            field=models.BooleanField(default=False),
        ),
    ]
